tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
brew 'autoconf'
brew 'bash'
brew 'coreutils'
brew 'findutils'
brew 'freetype'
brew 'git'
brew 'grep'
brew 'imagemagick', args: ['with-webp']
brew 'jpeg'
brew 'libidn'
brew 'libpng'
brew 'libtool'
brew 'openssl'
brew 'pcre'
brew 'pkg-config'
brew 'rbenv'
brew 'rbenv-gem-rehash'
brew 'readline'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tree'
brew 'webkit2png'
brew 'webp'
brew 'wget', args: ['with-iri']
brew 'xz'
